### PR TITLE
Add github actions workflow to run tests

### PR DESCRIPTION
**Pull request by csaluski**
Note that it seems like tests don't pass right now, I'm unsure if this is an issue with the test configuration in GitHub Actions or if it's an issue with some regressions on the tests. 

Also note that this uses the Selenium Docker image in the steps of the workflow instead of as a service container, when I tried to use it as a service container it had issues that I believe were rooted in the fact that I couldn't attach it to the host network.

### CODE REVIEW

**Comment by tdhock** [comment]
looks like some of the test failures are easy fixes,
```
Deprecated: please use `expect_lt()` instead
```

**Comment by Csaluski** [comment]
See [test results](https://github.com/Csaluski/animint2/actions/runs/2374340656) on my fork of the repo, I think this should be ready to merge. One thing worth double checking is the change to the widerect test I made, I commented the issues I was having that lead me to change it but it would be good to figure out exactly why it wasn't working.

**Comment by tdhock** [comment]
looks great +1 please update NEWS/DESCRIPTION with increased version number, then merge with master.

**Comment by Csaluski** [comment]
@tdhock the tests need a Github PAT with Gist access added to the repo secrets before they'll pass, I believe you're the only person who can set this up.

Also note that the build was also failing because of a trailing space on the Version tag in DESCRIPTION, I fixed that on my branch but I'm not sure if we should make a whole new PR for that.

**Comment by tdhock** [comment]
OK thanks for the info, I believe this should be fixed now on master.

**Pull request merged**
