### PR TITLE
fix for test failures

### PR DESCRIPTION
**Pull request by tdhock**
it seems like lots of tests are failing on other branches. this is an attempt to fix those test failures.

### CODE REVIEW

**Comment by vivekktiwari** [comment]
@tdhock @faizan-khan-iit 

The only major change in code of `validate-params` branch was changing validate_params =TRUE as default: [9fdd391678d9cbafa0a1a6d35e50919322bc2cbd](https://github.com/faizan-khan-iit/ggplot2/commit/9fdd391678d9cbafa0a1a6d35e50919322bc2cbd)

So, I undo that change, then I removed ```ggplot2Animint```,  re-installed, open a New Session for ```animint2``` then ran ```devtools::check()``` on ```animint2```.

test suite is still failing. 
```R
checking tests ... ERROR
  Running 'testthat.R'
``` 
I can't even see what is causing the error as there is no error statement. I also did ```devtools::test()``` and errors are same in both cases. 

I checked ```testthat.R```, should we not import ```library(ggplot2Animint)``` there?

**Comment by vivekktiwari** [comment]
@tdhock, as of now, `ggplot2Animint` on `validate-params` branch is failing Travis CI with following error (does this has any effects on tests?): 

```R
checking examples ... ERROR
Running examples in ‘ggplot2Animint-Ex.R’ failed
The error most likely occurred in:
> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: stat_summary_bin
> ### Title: Summarise y values at unique/binned x x.
> ### Aliases: stat_summary_bin stat_summary
> 
> ### ** Examples
> 
> d <- ggplot(mtcars, aes(cyl, mpg)) + geom_point()
> d + stat_summary(fun.data = "mean_cl_boot", colour = "red", size = 2)
> 
> # You can supply individual functions to summarise the value at
> # each x:
> d + stat_summary(fun.y = "median", colour = "red", size = 2, geom = "point")
Error: ScalesList was built with an incompatible version of ggproto.
Please reinstall the package that provides this extension.
Execution halted
** found \donttest examples: check also with --run-donttest
```

**Comment by tdhock** [comment]
the travis PR tests pass using the old version of ggplot2Animint, so I suspect some of your new commits to faizan-khan-iit/ggplot2@validate-params are causing the tests to break

**Comment by vivekktiwari** [comment]
@tdhock I have made only documentation changes to `ggplot2Animint`, just exported few functions, I will revert them, right away and try to find the reason of it.

**Comment by vivekktiwari** [comment]
removed all the changes made by me in `validate-params` branch, please retest Travis build with branch

**Comment by tdhock** [comment]
I'm merging this branch for now, so that @adrianblanco can use travis tests in his PRs.

@vivekktiwari when you figure out how to fix it please submit a PR. In my opinion the only real fix for this is by adding the ggplot2Animint code into animint2 -- otherwise, the tests could break again. That is, if you change ggplot2Animint code in a way that breaks animint2, there should be an easy way  (like travis) to see that it breaks -- right now you have no way of doing that -- and there is an easy way of doing that -- add ggplot2Animint code into animint2.

**Comment by vivekktiwari** [comment]
started working on merging, #18

**Comment by vivekktiwari** [comment]
#18

**Pull request merged**
