### PR TITLE
merge with new function names

### PR DESCRIPTION
**Pull request by vivekktiwari**

### CODE REVIEW

**Comment by vivekktiwari** [comment]
@faizan-khan-iit @tdhock please once have a look at the Travis Build, and let me know what is causing the error, I am unable to figure it out. All the test units are failing. 

I have kept both options open for now. 

1. `animint2` with `ggplot2animint` as a separate package (See #24 )
2. `animint2` with merged code (with new changes) (This one #25 )
3. `animint2 with merged code (old code with few changes) (See #23 )

**Comment by faizan-khan-iit** [comment]
@vivekktiwari At first look, it seems to be problem with Travis. I have restarted the build. Will see if that helps

**Comment by tdhock** [comment]
in these cases where you don't understand travis build results @vivekktiwari try running the tests on your own computer

**Comment by faizan-khan-iit** [comment]
@vivekktiwari Also, you don't need to work on 3 parallel options. As far as I remember, @tdhock suggested merging the code citing the reason that it would easier to merge the code considering the Travis builds. So you can focus on that

**Comment by vivekktiwari** [comment]
@faizan-khan-iit understood! It was just so that I can narrow down the changes, and compare the changes done, helps with debugging (while changing function names) but will try to avoid that. 

@tdhock I tried that, but `traceback()` aren't helping much as they were helpful with `ggplot2` code. 
I also tried to go through the code line by line, but couldn't seem to find the reason.

**Comment by vivekktiwari** [comment]
Summary of the changes made so far: 

1. `ggplot` is `a_plot` 
2. `ggplot_build` is `a_plot_build`
3. `ggplot_gtable` is `a_plot_gtable`
4. `ggproto` is `a_ggproto` (all function with `ggproto` name replaced to `a_ggproto`.
5. `facet` is `a_facet`. 
6. all `facet_*` function have been replaced with `a_facet_*` like `a_facet_grid` and many more. 
7. All `a_ggproto` class function replaced with a_ prefix like `a_Geom`, `a_Stat`, `a_Position` which are inherited. 
8. Renamed similar name function: `train_layout` is `a_train_layout` from (`ggplot2Animint`) `panel.R` as `train_layout` (with slight variation in code) is already present in `animint2` (`z_facets.R`)
9. Exported few functions from `animint2`
10. Removed `ggplot2Animint::` references from test units, examples and code.

**Comment by tdhock** [comment]
sounds good so far

have you started to look at trying to get the tests passing?

**Comment by vivekktiwari** [comment]
@tdhock finally, all test cases are passing....

**Comment by vivekktiwari** [comment]
@tdhock, @faizan-khan-iit, how should I proceed next? 

Should I change all other functions that are being masked from ggplot2?

**Comment by faizan-khan-iit** [comment]
I think its a good idea to avoid name clashes with `ggplot2` entirely

**Comment by vivekktiwari** [comment]
@faizan-khan-iit hi, sure. Working on it. 

But there are still more than 250+ functions that are being masked from `ggplot2`, making them `keywords internal` was not helping as `animint2` would have taken function from `ggplot2` NAMESPACE of same name causing `Error: attempt to apply non-function`

**Comment by vivekktiwari** [comment]
@faizan-khan-iit @tdhock "Just a Quick Summary"

I have renamed almost 80% of the function, all `geom_*`, `stat_*`, `coord_*`, `scale_*`, `theme_*` and `fortify_*` have been changed with `a_*` prefix, will be working on further functions and will try to finish it ASAP. 

Also wanted to ask, should we bring the test cases of `ggplot2Animint` in test-compiler-*.R after completing the changes, as this would help in recognizing errors of `ggplot2` functions if someone makes changes in them directly here (or in future) ?

**Comment by tdhock** [comment]
I think it would be a good idea to copy/modify the ggplot2 test cases as test-compiler-*.R files

**Comment by tdhock** [comment]
is there a test that explicitly loads/attaches ggplot2 and animint2 at the same time and verifies that everything is working fine? (I would assume that such a test would need to exist outside of the testthat infrastructure, e.g. tests/compatibility.R)

**Comment by vivekktiwari** [comment]
@tdhock @faizan-khan-iit I am trying to run tests in linux system locally. 
I am getting this error `Error in RSelenium::phantom() : PhantomJS binary not located.`
Tried researching, couldn't find actual solution.

Can you help me how to get rid of it? 
I am trying to figure why I am getting three failed test cases.

**Comment by vivekktiwari** [comment]
Resolved this one, working on errors now!
> I am getting this error Error in RSelenium::phantom() : PhantomJS binary not located.

**Pull request closed without merging**
